
package vista;

import javax.swing.JOptionPane;


/**
 *
 * @author USER
 */
public class Registroclientes extends javax.swing.JFrame {

    /**
     * Creates new form Registroclientes
     */
    public Registroclientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Txtusua = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Txtfono = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        psword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        btnregistrarse = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        Txtcorreo2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("registrese aqui");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 240, 70));

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 3, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/camarero (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 110, 130));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 3, 18)); // NOI18N
        jLabel6.setText("Nombre de usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, -1));
        getContentPane().add(Txtusua, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 130, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 3, 18)); // NOI18N
        jLabel1.setText("Telefono");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 70, -1));
        getContentPane().add(Txtfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 130, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 3, 18)); // NOI18N
        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 120, -1));
        getContentPane().add(psword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 130, -1));

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 3, 18)); // NOI18N
        jLabel7.setText("Correo electronico");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, -1));

        btnregistrarse.setBackground(new java.awt.Color(102, 102, 102));
        btnregistrarse.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btnregistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnregistrarse.setText("registrarse");
        btnregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 30));

        btncancelar.setBackground(new java.awt.Color(102, 51, 255));
        btncancelar.setFont(new java.awt.Font("Gill Sans MT", 3, 14)); // NOI18N
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 110, -1));

        Txtcorreo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtcorreo2ActionPerformed(evt);
            }
        });
        getContentPane().add(Txtcorreo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plum (2).jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarseActionPerformed
                                         
                                                 
    String usuario = Txtusua.getText();
    String telefono = Txtfono.getText();
    String contrasena = new String(psword.getPassword());
    String correo = Txtcorreo2.getText();
  
    if (usuario.isEmpty() || telefono.isEmpty() || contrasena.isEmpty() || correo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    conex.loginDao dao = new conex.loginDao();
    conex.login nuevoUsuario = new conex.login();

    nuevoUsuario.setNombreCompleto(usuario);
    nuevoUsuario.setCorreo(correo);
    nuevoUsuario.setTelefono(telefono); // ✅ ¡Esta línea es clave!
    nuevoUsuario.setContrasena(contrasena);
    nuevoUsuario.setRol("cliente");

      boolean registrado = dao.Registrar(nuevoUsuario);
    if (registrado) {
        JOptionPane.showMessageDialog(this, "Usuario registrado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        
        // Aquí abres el formulario principal y cierras el de registro:
        frmsistema sistema = new frmsistema();
        sistema.setVisible(true);
        this.dispose();

    } else {
        JOptionPane.showMessageDialog(this, "Error al registrar usuario", "Error", JOptionPane.ERROR_MESSAGE);
    }




  

// Ya no necesitas esta comparación porque no hay confirmar contraseña
// if (!contrasena.equals(confirmarContrasena)) {
//     JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
//     return;
// }


    // Aquí deberías agregar la lógica para registrar el usuario en la base de datos
    // Por ejemplo, utilizando el `loginDao` que mencionaste antes.

    // Si todo está bien, mostrar un mensaje de éxito
    JOptionPane.showMessageDialog(this, "Usuario registrado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);

    // Cerrar el formulario de registro
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistrarseActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
    this.dispose(); // Cierra la ventana de registro    // TODO add your handling code here:
    }//GEN-LAST:event_btncancelarActionPerformed

    private void Txtcorreo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtcorreo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtcorreo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registroclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registroclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registroclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registroclientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registroclientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Txtcorreo2;
    private javax.swing.JTextField Txtfono;
    private javax.swing.JTextField Txtusua;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnregistrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField psword;
    // End of variables declaration//GEN-END:variables
}
